### ISSUE TITLE
[Bug] The JuliaHealth logo issue

### ISSUE THREAD

**Issue by Jay-sanjay** [JuliaHealth/JuliaHealthWebsiteOld#120]
I found that the juliahealth logo seems to be deformed on Android interface, image attached

![image](https://github.com/JuliaHealth/juliahealth.github.io/assets/134289328/b73c4b61-44d0-4bf7-8abb-0aa7f3a76997)

@TheCedarPrince could you please look over it once . Thanks !!

**Comment by cormullion** [comment]
I think ... the problem with specifying **both** `width` and `height` percentages is that they'll be applied to the image container's dimensions rather than to the image's. 

If you just specify `width`, the `height` will then be calculated automatically, and preserve the aspect ratio:

```
<img src="/assets/julia-health-logo.png" alt="JuliaHealth logo" title="JuliaHealth logo" style="width: 25%; align:center">
```

**Comment by TheCedarPrince** [comment]
Fix has been submitted! Thanks @cormullion for the fix and @Jay-sanjay for reporting this issue!
