### ISSUE TITLE
Remove the iguana

### ISSUE THREAD

**Issue by tlienart** [JuliaHealth/JuliaHealthWebsiteOld#18]
Same small issue as the first point of https://github.com/JuliaSymbolics/SymbolicUtils.jl/issues/43 basically either remove the `favicon` line in `_layout/head.html` or replace the `_assets/favicon.png` 

I should remove that iguana in the templates, I had it there for fun in the beginning but now I think I probably should make it a big red question mark or something 😱

**Comment by DilumAluthge** [comment]
I totally meant to replace it with the JuliaHealth favicon but completely forgot.
